name: Raise Pull Request

env:
  GITHUB_USER_NAME: 'shivam779823'
  GITHUB_USER_EMAIL: 'mshivam110@gmail.com'

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow on,
  pull_request:
    branches:
      - main
    types:
      - reopened
      - opened
      - synchronize 
  workflow_dispatch:

jobs:
  raise_pull_request:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      id-token: write
      pull-requests: write
      security-events: write
      repository-projects: write
      checks: write
      deployments: write
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:  
          fetch-depth: 0

      # - name: Fetch branch from remote
      #   run: git fetch origin last:refs/remotes/origin/${{ github.head_ref }}
  
  
      - name: Find last changed file
        id: find
        run: |
          # Get the most recent commit in the pull request branch
          MOST_RECENT_COMMIT=$(git log --format="%H" -n 1 origin/${{ github.head_ref }})
  
          # Get the list of changed files in the most recent commit
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r $MOST_RECENT_COMMIT | grep '\.txt$' | tail -n 1)
  
          # Display the last changed file
          echo "Most recent change: $CHANGED_FILES"
          echo "$CHANGED_FILES"
          if [[ "$CHANGED_FILES" == "test.txt" ]] ; then TFVARS="requirements.txt" ; fi
          if [[ "$CHANGED_FILES" == "dev.txt" ]] ; then TFVARS="dev-requirements.txt" ; fi
          echo "$TFVARS"

      - name: Checkout destination code
        uses: actions/checkout@v2
        with:
          path: 'dest'
          persist-credentials: true
          repository: shivam779823/dustbin
          token: ${{ secrets.API_TOKEN_GITHUB }}
          ref: test
          fetch-depth: 0   
      - name: if tfvars selection
        run: | 
          
      - name: make change
        working-directory: dest
        run: |
          cd ..
          ls
          T="$(echo $CHANGED_FILES )"
          cd dest
          echo $T >> $CHANGED_FILES
      
      - name: Set up Git
        working-directory: dest 
        run: |
          git remote set-url origin https://${{ github.GITHUB_ACTOR }}:${{ secrets.API_TOKEN_GITHUB }}@github.com/shivam779823/dustbin.git 
          git config user.name "${{ env.GITHUB_USER_NAME }}"
          git config user.email "${{ env.GITHUB_USER_EMAIL }}"
      - name: Commit changes
        working-directory: dest 
        run: |
          git checkout test
          git add .
          git commit -m "Automated changes"
      - name: Push changes
        working-directory: dest 
        run: |
          git push origin test


