name: Compare Files on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  compare_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:  
          fetch-depth: 0

      - name: Checkout destination code
        uses: actions/checkout@v2
        with:
          path: 'dest'
          persist-credentials: true
          repository: shivam779823/dustbin
          token: ${{ secrets.API_TOKEN_GITHUB }}
          ref: test
          fetch-depth: 0    

      - name: Find last changed files
        id: find
        run: |
          # Get the list of changed files in the pull request
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'user.txt')
          
          # Display the changed files
          echo "Changed files: $CHANGED_FILES"
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Compare files
        run: |
          CHANGED_FILES="${{ steps.find.outputs.changed_files }}"
          
          # Check if user.txt is among the changed files
          if echo "$CHANGED_FILES" | grep -q 'user.txt'; then
            # Compare user.txt with locals.tfvars in the destination repository
            diff_result=$(diff user.txt dest/locals.tfvars || true)
            
            # Check if there are differences
            if [ -n "$diff_result" ]; then
              echo "Files are different. Diff result:"
              echo "$diff_result"
            else
              echo "Files are identical."
            fi
          else
            echo "user.txt not among the changed files."
          fi
